name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Print Haxe version
        run: haxe --version

      - name: Build Heaps iframe example
        run: npm run build:heaps-iframe-build

      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          with-deps: true

      - name: Run Playwright tests
        run: npm test